### ISSUE TITLE
Defect: CMake can't find mpiexec if not in PATH

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#359] opened 2017-04-14 04:13 UTC
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

 - [X] I have surrounded any code, or log output in codeblock fences
       (` ``` `) if it occupies more than one line, or in single
       backticks if it is short `short code`

# Defect/bug report #

With the current master branch (OpenCoarrays 1.8.5) and MPICH 3.1.4, although though [line 27] in the build_opencoarrays.sh script sets the CC and FC environment variables and passes the MPI_C_COMPILER and MPI_Fortran_COMPILER arguments, CMake reports that it can't find mpiexec (despite finding mpif90)) unless mpiexec is in the PATH:
```bash
CC="${CC}" FC="${FC}" $CMAKE "${opencoarrays_src_dir}" \
  -DCMAKE_INSTALL_PREFIX="${install_path}" \
  -DMPI_C_COMPILER="${MPICC}" \
  -DMPI_Fortran_COMPILER="${MPIFC}"
```
The above behavior happens with our default CMake 3.4.0.  I'm investigating whether updating to a newer CMake version would resolve this or whether we simply need to set add the MPICH bin directory to the PATH before the above statement executes (which seems like overkill).   Depending on the outcome of my investigations, I'll either edit the build_opencoarrays.sh script to adjust the PATH before the above statement executes or I'll bump the minimum CMake version number.  I'll also look into bumping the MPICH version number as requested in issue #355.

The title of the issue should start with `Defect:` followed by a
succinct title.

 - [ ] I have searched the [issues page] and [mailing list] and did
       not find any issue matching the one I would like to report
 - [X] I have included a succinct description of the problem,
       including the steps necessary to reproduce it
 - [X] I have included which version of OpenCoarrays I am working
       with, or the output of `git describe` if working with a cloned
       repository rather than an [official release]
 - [X] I have included the MPI library name and version I am using
       with OpenCoarrays
   - [ ] name: [MPICH] version: 3.1.4
 - [X] I have included the Fortran compiler name and version that I am
       using with OpenCoarrays: 7.0.1
 - [ ] I have included the output of `uname -a`:  
`Linux rouson-VirtualBox 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
 - [X] I have included the Operating system name and version,
       including linux distro: Lunbuntu 16.10
 - [X] I have included the machine name if I am allowed to do so and
       wish to seek help debugging on that particular system (Titan,
       Pleiades, Excalibur, Lightening, Mira, etc.): MacBook Pro

## Installation/build problem ##

**Please select one from the following top level items** (please be sure to fill out all sub-items)**:**
 - [X] Build/install was attempted with [install.sh]
    - [ ] I have attached the `install-opencoarrays.log` file
          after re-running the script with the debug flags `-d` and
          `-v` turned on (after renaming the log file to have a `.txt`
          extension)
 - [ ] Build/install was attempted with system package manager like
       [homebrew] (which one?)
 - [ ] Build/install was attempted with manual/advanced
       [CMake install]
   - [X] Name and version of the C compiler being used: gcc
     - [X] Name and version of the Fortran compiler being used: gfortran
     - [X] Attached/included the output of the configure step with
           CMake. (Usually something like `cd build && cmake ..`):  see above
     - [ ] Attached/included the output of `make VERBOSE=1`
     - [ ] Attached/included the output of `ctest --verbose`
 - [X] Other build/install was attempted (please describe): macOS build under way

## Compile time or run time error

**Please choose one of the first two items**
 - [X] I am experiencing a compile time error (all gfortran ICEs
       should be reported to the [GFortran bug tracker]... You can post
       the ICE here too for tracking purposes, with a link to the
       GFortran problem report)
 - [ ] I am experiencing a runtime issue

**:sparkles: Optional, but you will receive infinite karma for including this: :sparkles:**
 - [X] I have included a minimally complete verifiable example (MCVE)
       that exhibits the problem and suitable for adding to regression
       tests: the example is the new [patched-trunk-install.sh] script.

[links]:#
[GFortran bug tracker]: https://gcc.gnu.org/bugzilla/
[Intel MPI]: https://software.intel.com/en-us/intel-mpi-library
[MPT]: http://www.sgi.com/products/software/sps.html
[MVAPICH]: http://mvapich.cse.ohio-state.edu
[MPICH]: https://www.mpich.org
[Open-MPI]: https://www.open-mpi.org
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[official release]: https://github.com/sourceryinstitute/OpenCoarrays/releases
[CMake install]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#cmake-scripts
[homebrew]: http://brew.sh
[issues page]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[mailing list]: https://groups.google.com/forum/#!forum/opencoarrays
[install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/install.sh
[issue stat img]:https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[lin 27]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/prerequisites/install-functions/build_opencoarrays.sh#L27
[patched-trunk-install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/developer-scripts/patched-trunk-install.sh

**Comment by rouson** [comment] 2017-04-14 05:05
I've now confirmed this behavior happens with a much more recent version of CMake (3.7.1) and with a slightly older version of gfortran (6.2.0) installed by package management (whereas the gfortran installation in the initial report was installed by the OpenCoarrays installer). This appears to be general and longstanding behavior of CMake.

**Comment by rouson** [comment] 2017-04-14 14:03
And similar behavior happens on macOS.  With the following, CMake finds the mpiexec in the PATH rather than the one in the location of the specified compilers:
```bash
CC="/Users/rouson/Code/opencoarrays/prerequisites/installations/gcc/trunk/bin/gcc" \
FC="/Users/rouson/Code/opencoarrays/prerequisites/installations/gcc/trunk/bin/gfortran" \
cmake "/Users/rouson/Code/opencoarrays" \
-DCMAKE_INSTALL_PREFIX="/Users/rouson/Code/opencoarrays/prerequisites/installations/" \
-DMPI_C_COMPILER="/Users/rouson/Code/opencoarrays/prerequisites/installations/mpich/3.1.4/bin/mpicc" \
-DMPI_Fortran_COMPILER="/Users/rouson/Code/opencoarrays/prerequisites/installations/mpich/3.1.4/bin/mpif90"
```

**Comment by zbeekman** [comment] 2017-04-14 14:48
Hi Damian (@rouson),

So is this issue occurring when using `install.sh`, or with manual invocation of cmake?

If you're manually invoking CMake, perhaps a better thing to try, before jumping to `-DMPI_C_COMPILER` and `-DMPI_Fortran_COMPILER` would be setting your `MPI_HOME` variable in the environment, or ensuring that the MPI you wish to use is first on your `PATH`.

Unless this is a problem when using `install.sh`, then I think this can be tagged as an upstream, CMake issue and closed as "won't fix" since the issue surrounds CMake's behavior and our manually invocation can be adjusted accordingly.

If this issue is arising with `install.sh` then I'll take a look and try to find a better way to tell CMake which MPI implementation to use.

**Comment by rouson** [comment] 2017-04-14 14:51
The same behavior occurs when I invoke CMake directly so I think you're correct that this is upstream.  I see that you assigned this issue to yourself so I'll let you close it and mark it as "won't fix."  I'm working on a simple reproducer for CMake.

**Comment by rouson** [comment] 2017-04-14 14:53
I have the reproducer now.  I'll report it to Kitware later this morning.

**Comment by zbeekman** [comment] 2017-04-14 15:32
Oh, but it happens when the install.sh script is used as well? In that case we should look into a way to work around this or at least produce more consistent behavior.

**Comment by zbeekman** [comment] 2017-04-14 15:33
also, would you mind sharing your reproducer? That will help me understand the expected vs observed behavior

**Comment by rouson** [comment] 2017-04-14 16:53
On second thought, let's keep this open until we have a workaround in place.  I think the workaround, as you suggested, is to put the desired MPI installation in the PATH before invoking CMake.  I'll submit the issue to CMake today and then will submit a pull request with the workaround unless you'd like to do so before I get to it.  It will be a few hours before I get to it.  I'll attach the reproducer to my next comment.

**Comment by rouson** [comment] 2017-04-14 17:09
Here's the reproducer that I'll submit to Kitware later today: [cmake-issue.zip](https://github.com/sourceryinstitute/OpenCoarrays/files/922547/cmake-issue.zip)

And here's the included README file:

[This document is formatted in GitHub-flavored Markdown]:#

CMake Issue Reproducer: MPIEXEC not found even if arguments specify MPI compiler locations
==========================================================================================

## Issue demonstration
To demonstrate the issue, execute the following at the command line in a bash shell:
```bash
cd cmake-issue
./cmake-issue.sh
```
which takes about 6 minutes to run inside a Lubuntu Linux virtual machine given access to all four cores on a 2017 MacBook Pro laptop.  Near the bottom of the output is the message that represents the issue:

-- MPIEXEC=MPIEXEC-NOTFOUND

## Sample output

Included in this archive is the output file cmake-issue.log from executing
```bash
time ./cmake-issue.sh >& cmake-issue.log
```
in a bash shell inside a nearly bare Lubuntu Linux virtual machine with GCC 6.2 and CMake 3.5.2 installed.  Previous tests indicate that the same behavior is obtained with CMake 3.4.0 and 3.7.1 and the same behavior is observed on macOS Sierra.

**Comment by rouson** [comment] 2017-04-14 18:50
This is now CMake [issue 16804](https://gitlab.kitware.com/cmake/cmake/issues/16804).

**Comment by rouson** [comment] 2017-04-15 15:55
I'll submit a pull request shortly that contains a commit that works around this CMake issue. I'll attempt to close the pull request via the commit message.

**Comment by zbeekman** [comment] 2017-04-15 16:13
>I'll attempt to close the pull request via the commit message.

you mean close the issue via the pull request commit comment, I presume...

Just wondering, what is going to be you're approach? Setting PATH in the script? If you do that, I would recommend restoring the users old PATH after the install finishes, or else people may install it, test it, and then later have path issues... at least until #268 is done.... yeah I have a huge backlog to look  at.  Might find time today.

**Comment by zbeekman** [comment] 2017-04-15 17:07
Perhaps more evidence that I need to adjust the issue/pr templates to make them clearer and more concise:

> I'll attempt to close the pull request via the commit message.

It doesn't *really* matter if the issue is closed through the comment, the most important part is that the commit message mentions the issues. This way a link is produced on the issue page to the commit and a link in the commit is created to the issue page. 

One less important, but still useful property of closing via the commit message is that the issue being open indicates that the fix is not on master yet. If you create a commit on a branch closing the issue, the issue gets closed when merged back into master.

**Closed** 2017-04-25 00:50 UTC
Labels: build-system, confirmed, needs review
