### ISSUE TITLE
Allocate not correctly synchronizing on oversubscribed cores

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#243] opened 2016-11-07 00:02 UTC
EDIT by @zbeekman: GFortran [PR 78505](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78505)

The transcript below demonstrates that OpenCoarrays is not performing the synchronization required during the allocation of a coarray when the number of images exceeds the number of cores (8 images on 4 cores in the case below).  I can't think of a way to test the `allocate` without `source =` because
 
1. The coarray cannot be defined before the `allocate` and
2. A definition of the coarray immediately after the `allocate` would happen asynchronously.

The workaround is to add some form of synchronization (e.g., `sync all`) after the `allocate`, but requiring that does not conform with the standard.

```
$ cat source-allocation-not-syncing.f90 
 implicit none
 integer, allocatable :: f(:)[:]
 integer, parameter :: num_points=32
 integer :: me,ni,my_num_points,neighbor_last_element
 me = this_image()
 if (mod(num_points,num_images())/=0) error stop "num_points not evenly divisible by num_images()"
 my_num_points = num_points/num_images()
 allocate( f(my_num_points)[*], source = 1 )
 if (me>1) then 
   neighbor_last_element = f(my_num_points)[me-1]
   if (neighbor_last_element /=1) print *,"Image ",me," gets ",neighbor_last_element
 end if
end 

$ caf source-allocation-not-syncing.f90 
$ cafrun -np 8 ./a.out
 Image            5  gets            0
$ cafrun -np 8 ./a.out
 Image            3  gets            0
 Image            5  gets            0

$ caf --wraps
caf wraps CAFC=/opt/mpich/3.1.4/gnu/7.0.0/bin/mpif90

$ /opt/mpich/3.1.4/gnu/7.0.0/bin/mpif90 --version
GNU Fortran (GCC) 7.0.0 20160904 (experimental)
...
```

**Comment by rouson** [comment] 2016-11-07 00:05
FYI, I believe the gfortran above gfortran date (20160904) precedes the first commit in support of allocatable components and I observe the same behavior with gfortran 6.2.0 so I suspect this behavior is not due to any recent commits.

**Comment by afanfa** [comment] 2016-11-11 03:09
If you remove the source=1 as argument you should see the correct behavior. Having the source=1 in the allocation statement gives you the illusion that the assignment happens during the allocation but actually it happens right after. That's what causes the bug.
There is nothing I can do in the library for this specific case because it is managed by the compiler.

**Comment by rouson** [comment] 2016-11-11 17:42
@afanfa, I'll file a compiler bug report.  Let's keep this open until it's fixed on the compiler side.  I wonder we should have a subset of our tests for regression testing and add this code to that suite.  That way users are alerted of the issue and know that they'll need to modify their code to work around it. @zbeekman, thoughts?

**Comment by zbeekman** [comment] 2016-11-23 21:51
@rouson do you have a GCC PR# for this issue?

@rouson I'm a bit confused as to what exactly you're envisioning. A set of tests that are expected to fail until GCC patches the relevant issues? If so, I think that's a great idea!

**Comment by rouson** [comment] 2016-11-24 09:18
GFortran [PR 78505](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78505)

**Comment by vehre** [comment] 2016-11-25 12:14
@rouson Can you add the paragraph of the standard that mandates, that allocation and definition in an ALLOCATE() are atomic?

**Comment by rouson** [comment] 2016-11-25 15:57
Section 9.7.1.2, paragraph 4:

"When an ALLOCATE statement is executed for which an allocate-object is a coarray, there is an implicit synchronization of all active images in the current team. On those images, if no error condition other than STAT_STOPPED_IMAGE or STAT_FAILED_IMAGE occurs, execution of the segment (11.6.2) following the statement is delayed until all other active images in the current team have executed the same statement the same number of times in this team. The coarray shall not become allocated on an image unless it is successfully allocated on all active images in this team."

The important point is that no image can execute the segment following the ALLOCATE statement until every image has executed the ALLOCATE statement the same number of times (once in the example submitted in PR 78505).  Because the "SOURCE=" is part of the ALLOCATE statement, the action indicated by the "SOURCE=" must complete on every image before any image can execute code that comes after the corresponding ALLOCATE.

**Comment by vehre** [comment] 2017-01-09 11:27
IMO this issue can be closed. PR78505 has been committed to gcc-trunk and the issue in ocaf is not to occur anymore.

**Comment by zbeekman** [comment] 2017-01-09 16:41
> IMO this issue can be closed. PR78505 has been committed to gcc-trunk and the issue in ocaf is not to occur anymore.

@vehre I'll confirm this is resolved and then if so, I will close this issue.

**Comment by zbeekman** [comment] 2017-01-09 16:41
Also, I'll add this to the regression tests.

**Comment by vehre** [comment] 2017-01-10 10:34
Er, I don't get why I got this issue back. What do you expect me to do?
The issue can be closed, because it is superseded by #260 and the tracking of the issue can be done there. Also is the testcase already present, so I have no clue, what I am to do here!

**Comment by zbeekman** [comment] 2017-01-10 17:22
@vehre hey, sorry... yes my mistake.

**Comment by zbeekman** [comment] 2017-01-14 20:01
@rouson did we ever add a regression test for this? It doesn't look like it, please correct me if my understanding is wrong...

**Comment by zbeekman** [comment] 2017-01-15 21:40
I've added a regression test for this, and confirmed that as of at least
> GNU Fortran (Homebrew GCC HEAD-244466_1 --without-multilib) 7.0.0 20170114 (experimental)

That this issue has been resolved.

**Closed by zbeekman** 2017-01-15 21:40 UTC
Labels: Quality Assurance, ready, upstream-compiler-bug, waiting

**Comment by zbeekman** [comment] 2017-01-16 17:02
@vehre: Is there a good way to tell if the compiler being used has the changes from GFortran [PR 78505](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78505) integrated in it? (Assuming this fix gets back-ported to GCC 5 and 6... or will this only be fixed on the >= 7 branch? I ask, because I created a regression test for this, but then I realized that on our CI infra we are only testing with GFortran 6.2/6.3 currently... and it appears that this fix hasn't made it into 6.3. So I need to conditionally enable them based on whether the compiler contains the fix.

**Comment by vehre** [comment] 2017-01-16 17:13
What is a "good way" for you? Publicy available on a binary is only the version. In the source code one can of course the Changelog, where the pr is referenced, but that must not necessarily mean the pr has been fully fixed, but can also mean, that an error message has been added or something similar.

I will investigate what backporting takes.

**Comment by vehre** [comment] 2017-01-16 17:25
Backporting takes some significant work. It will most likely not being done.

**Comment by zbeekman** [comment] 2017-01-16 17:34
OK, that's fine. A good way, I guess is just knowing which versions it is in and which it is not, if it's only in trunk/7 onwards. Thanks!
