### ISSUE TITLE
Build failure with cmake/gnu 6.0/opencoarrays 1.3.8

### ISSUE THREAD

**Issue by sfilippone** [sourceryinstitute/opencoarrays#164] opened 2016-04-07 14:24 UTC
Hi there, I just got this error when trying to build 1.3.8 with a fresh install from source of GNU 6.0
-----------------------------------------------
e802756@sow768056c-li [111] 03:20 PM [build] CC=mpicc FC=mpif90 cmake .. -DCMAKE_INSTALL_PREFIX=/opt/OpenCoarrays/1.3.8/mpich/3.2.0/gnu/6.0.0 
-- The C compiler identification is GNU 6.0.0
-- The Fortran compiler identification is GNU 6.0.0
-- Check for working C compiler: /opt/mpich/3.2.0/gnu/6.0.0/bin/mpicc
-- Check for working C compiler: /opt/mpich/3.2.0/gnu/6.0.0/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /opt/mpich/3.2.0/gnu/6.0.0/bin/mpif90
-- Check for working Fortran compiler: /opt/mpich/3.2.0/gnu/6.0.0/bin/mpif90  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/mpich/3.2.0/gnu/6.0.0/bin/mpif90 supports Fortran 90
-- Checking whether /opt/mpich/3.2.0/gnu/6.0.0/bin/mpif90 supports Fortran 90 -- yes
-- Performing Test Check_Simple_Coarray_Fortran_Source_Compiles
-- Performing Test Check_Simple_Coarray_Fortran_Source_Compiles - Success
-- Found MPI_C: /opt/mpich/3.2.0/gnu/6.0.0/lib/libmpi.so  
-- Found MPI_Fortran: /opt/mpich/3.2.0/gnu/6.0.0/lib/libmpifort.so;/opt/mpich/3.2.0/gnu/6.0.0/lib/libmpi.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/CCNT/e802756/NUMERICAL/OPENCOARRAYS/OpenCoarrays-1.3.8/build
e802756@sow768056c-li [112] 03:21 PM [build] make
Scanning dependencies of target caf_single
[  1%] Building C object src/single/CMakeFiles/caf_single.dir/single.c.o
[  2%] Building C object src/single/CMakeFiles/caf_single.dir/__/common/caf_auxiliary.c.o
[  4%] Linking C static library libcaf_single.a
[  4%] Built target caf_single
Scanning dependencies of target caf_mpi
[  5%] Building Fortran object src/mpi/CMakeFiles/caf_mpi.dir/__/extensions/opencoarrays.F90.o
[  7%] Building C object src/mpi/CMakeFiles/caf_mpi.dir/mpi_caf.c.o
[  8%] Building C object src/mpi/CMakeFiles/caf_mpi.dir/__/common/caf_auxiliary.c.o
[ 10%] Linking Fortran static library libcaf_mpi.a
[ 10%] Built target caf_mpi
Scanning dependencies of target hello_multiverse
[ 11%] Building Fortran object src/tests/integration/coarrayHelloWorld/CMakeFiles/hello_multiverse.dir/hello_multiverse.F90.o
[ 12%] Linking Fortran executable hello_multiverse
[ 12%] Built target hello_multiverse
Scanning dependencies of target coarray_distributed_transpose
[ 14%] Building Fortran object src/tests/integration/dist_transpose/CMakeFiles/coarray_distributed_transpose.dir/coarray_distributed_transpose.F90.o
[ 15%] Linking Fortran executable coarray_distributed_transpose
CMakeFiles/coarray_distributed_transpose.dir/coarray_distributed_transpose.F90.o: In function `MAIN__':
coarray_distributed_transpose.F90:(.text+0x1f5d): undefined reference to `_gfortran_caf_stop_str'
collect2: error: ld returned 1 exit status
make[2]: *** [src/tests/integration/dist_transpose/coarray_distributed_transpose] Error 1
make[1]: *** [src/tests/integration/dist_transpose/CMakeFiles/coarray_distributed_transpose.dir/all] Error 2
make: *** [all] Error 2
e802756@sow768056c-li [113] 03:23 PM [build] module li 
Currently Loaded Modulefiles:
  1) cmake/3.4.1   2) gnu/6.0.0     3) mpich/3.2.0   4) gdb/7.10
e802756@sow768056c-li [114] 03:23 PM [build] gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/opt/gnu/6.0.0/libexec/gcc/x86_64-pc-linux-gnu/6.0.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --prefix=/opt/gnu/6.0.0 --enable-languages=c,c++,fortran
Thread model: posix
gcc version 6.0.0 20160407 (experimental) (GCC) 

--------------------------------------------------------------------------------------------------------------
If you need anything else please let me know. 
Salvatore

**Comment by zbeekman** [comment] 2016-04-07 15:11
Hi Salvatore,
Were you using the install.sh script or a manual CMake invocation? I am working on reproducing this, but it might take a while since I don't think I have GCC 6 installed at the moment...

**Comment by sfilippone** [comment] 2016-04-07 15:12
I was using a manual CMake invocation, because I keep various versions of
GCC/MPI around with my own modules...

**Comment by zbeekman** [comment] 2016-04-07 15:33
Thanks for the info. I am wondering if this is related to #160 and #162. The corresponding changes in OpenCoarrays (PR #162) have been merged into master but have not yet made it into a release. In addition, @afanfa committed some changes to GCC trunk and 5.x branch.

It is going to be quite some time before I finish building GCC 6, but, in the mean time, could you please trying to build OpenCoarrays directly from the master branch? If my hunch is right there's a good chance that this will resolve the broken GCC 6 build for you.

**Comment by afanfa** [comment] 2016-04-09 14:58
Using a fresh gcc-trunk and opencoarrays master branch installation, I'm not able to reproduce Salvatore's bug. CMake does compile correctly every test case.
Running ctest, only the navier-stokes solver fails. Unfortunately I cannot reproduce this error manually (compiling and running the navier-stokes solver manually).

**Comment by zbeekman** [comment] 2016-04-09 15:10
Hi @afanfa I meant to update this thread with our latest communications: @sfilippone has confirmed that the bug is fixed on master. I will talk with @rouson about minting a release later today.

**Closed by zbeekman** 2016-04-09 15:10 UTC
Labels: bug
