### ISSUE TITLE
setup.csh generated by the OpenCoarray's installation process

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#607] opened 2018-11-08 16:06 UTC
OpenCoarrays 2.3.1 installation still has setup.csh errors.  Please make the lines of executable code look like this:

set path = ("<head>/OpenCoarrays-2.3.1/prerequisites/installations/cmake/3.4.0/bin" $path)                  
set path = ("<head>/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0"/bin $path)                    
setenv LD_LIBRARY_PATH "<head>/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib64/:<head>/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib:${LD_LIBRARY_PATH}"
set path = ("<head>/OpenCoarrays-2.3.1/prerequisites/installations/mpich/3.2"/bin $path)              
set path = ("<head>/OpenCoarrays-2.3.1/prerequisites/installations//opencoarrays/2.3.1"/bin $path)                      

where <head> is the directory where the tar file was untar'd.

**Comment by zbeekman** [comment] 2018-11-08 21:44
If I understand my csh research, should we be using `setenv` instead of `set`?

**Comment by zbeekman** [comment] 2018-11-08 21:44
related, duplicate of #584

**Comment by singleterry** [comment] 2018-11-08 22:59
Hello,

Here is what you get from the install:

set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/cmake/3.4.0/bin" "$path")
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0"/bin "$path")
set LD_LIBRARY_PATH = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib64/:/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib" "${LD_LIBRARY_PATH}")
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/mpich/3.2"/bin "$path")
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations//opencoarrays/2.3.1"/bin "$path")

Here is what it should be:

set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/cmake/3.4.0/bin" $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0"/bin $path)
setenv LD_LIBRARY_PATH "/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib64/:/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/gnu/8.2.0/lib:${LD_LIBRARY_PATH}"
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations/mpich/3.2"/bin $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.3.1/prerequisites/installations//opencoarrays/2.3.1"/bin $path)

Hope that helps.

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Closed** 2018-11-20 00:50 UTC
Labels: bug, build-system, needs-review
