### ISSUE TITLE
1.8.4 fails 3 tests with gcc 7.0.1

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/OpenCoarrays#339] opened 2017-03-08 08:52 UTC
```
10/40 Test #10: async_comp_alloc .................***Timeout   3.09 sec
37/40 Test #37: convert-before-put ...............***Failed  Required regular expression not found.Regex=[Test passed.
]  0.02 sec
40/40 Test #40: test-installation-scripts.sh .....***Failed    0.21 sec

93% tests passed, 3 tests failed out of 40

Total Test time (real) =  15.15 sec

The following tests FAILED:
         10 - async_comp_alloc (Timeout)
         37 - convert-before-put (Failed)
         40 - test-installation-scripts.sh (Failed)
```

This is on:

```
newblue4> caf -w
caf wraps CAFC=/panfs/panasas01/mech/mexas/soft/mpich-3.2-install/bin/mpif90
newblue4> which mpif90
/panfs/panasas01/mech/mexas/soft/mpich-3.2-install/bin/mpif90
newblue4> mpif90 --version
GNU Fortran (GCC) 7.0.1 20170226 (experimental)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

newblue4> uname -a
Linux newblue4 2.6.32-220.23.1.el6.x86_64 #1 SMP Mon Jun 18 09:58:09 CDT 2012 x86_64 x86_64 x86_64 GNU/Linux
newblue4> 
```

**Comment by mexas** [comment] 2017-03-08 09:30
and
```
newblue4> caf --version

OpenCoarrays Coarray Fortran Compiler Wrapper (caf version 1.8.4)
Copyright (C) 2015-2016 Sourcery, Inc.
```

**Comment by rouson** [comment] 2017-03-08 14:52
Thanks, @mexas.  These are known failures that I think only occur with gfortran 7.  (I'll research and post the corresponding issue numbers later today.) For now, we recommend that most people use gfortran 6.  However, if I recall correctly, you're interested in using allocatable components inside derived type coarrays.  That requires gfortran 7.    FYI, test 10 is a "performance bug": it causes a global synchronization to happen whenever an allocatable component in a derived type coarray gets allocated.  We're aware of this and intend to eliminate this unnecessary synchronization.  For now, the support for allocatable components of derived type coarrays should be considered experimental.

**Comment by mexas** [comment] 2017-03-08 15:00
Hi Damian. I thought so. Anyway, I sent this more as an extra data point for your optimisation work.
Anton

**Comment by zbeekman** [comment] 2017-04-25 01:12
This is attached to #342 (reminder to self, and to connect issues)

**Comment by zbeekman** [comment] 2017-05-07 04:07
- `async_comp_alloc` is a test of a partially implemented feature, test will pass when finished (see #260)
- `convert-before-put` is a known regression (#292)
- `test-installation-scripts.sh` failed due to ancient bash

Closing issue, since #342 has been implemented, preventing the first two tests from being run.

**Comment by zbeekman** [comment] 2017-05-07 04:07
I should add the install script test to the advanced developer tests...

**Closed by zbeekman** 2017-05-07 04:07 UTC
Labels: build-system, confirmed, ready

**Comment by zbeekman** [comment] 2017-05-08 14:27
Just a quick update: `40 - test-installation-scripts.sh (Failed)` looks like it may have had a permissions issue. A temporary fix is now on master, and I'm planning a more robust fix very soon. It's possible that this was failing due to an outdated Bash (2? Perhaps some very very old versions of 3 *could* __maybe__ have issues, but I'm hoping that the permissions error was the source of your problems and think that bash >= 3 should run this without issue.)
