### ISSUE TITLE
Defect: mvapich2 build fails to run tests

### ISSUE THREAD

**Issue by LaHaine** [sourceryinstitute/OpenCoarrays#517] opened 2018-03-12 10:14 UTC
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

Please make sure to put any logs, terminal output, or code in
[fenced code blocks]. Please also read the [contributing guidelines]
before submitting a new issue.

# Defect/Bug Report #

The title of the issue should start with `Defect:` followed by a
succinct title.

- OpenCoarrays Version: 
2.0.0
- Fortran Compiler: 
GNU 7.2.0
- C compiler used for building lib: 
GNU 7.2.0
- Installation method: 
install.sh
- Output of `uname -a`:
Linux obst25.zeuthen.desy.de 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 04:11:40 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
- MPI library being used: 
mvapich2 2.2
- Machine architecture and number of physical cores:
x86_64, 16 cores
- Version of CMake: 
cmake 3.9.2 from OpenHPC
## Observed Behavior ##
the build finishes, but there are linking problems when trying to build the tests
## Expected Behavior ##
tests should build and execute fine
## Steps to Reproduce ##
- install CentOS 7.4
- add OpenHPC repository
- build with the attached spec file with the --define mpi_family\ mvapich2 switch

Attached is the build log:
[build.log.txt](https://github.com/sourceryinstitute/OpenCoarrays/files/1802284/build.log.txt)
And the rpm SPEC file:
[opencoarrays.spec.txt](https://github.com/sourceryinstitute/OpenCoarrays/files/1802285/opencoarrays.spec.txt)

The output of caf -w is
caf wraps /opt/ohpc/pub/compiler/gcc/7.2.0/bin/gfortran

and caf -s is:
/opt/ohpc/pub/compiler/gcc/7.2.0/bin/gfortran -I/builddir/build/BUILD/OpenCoarrays-2.0.0/prerequisites/builds/opencoarrays/2.0.0/include/OpenCoarrays-2.0.0_GNU-7.2.0 -fcoarray=lib -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/mvapich2-gnu7/2.2/lib -Wl,--enable-new-dtags ${@} /builddir/build/BUILD/OpenCoarrays-2.0.0/prerequisites/builds/opencoarrays/2.0.0/lib64/libcaf_mpi.a /opt/ohpc/pub/mpi/mvapich2-gnu7/2.2/lib/libmpifort.so /opt/ohpc/pub/mpi/mvapich2-gnu7/2.2/lib/libmpi.so

**Comment by LaHaine** [comment] 2018-03-12 15:06
OK, I have researched this a bit, mvapich2 2.2 seems to be too old and doesn't have this binding yet. Maybe a configure check should be added for this?

**Comment by rouson** [comment] 2018-03-22 05:12
@LaHaine Feel free to submit a pull request with the suggested configure request.  Given other commitments, I don't think anyone else will do so.  For now, I'll close this issue now that you have determined the cause.

**Closed by rouson** 2018-03-22 05:12 UTC
