### ISSUE TITLE
Defect: 2 tests fail on macOS 10.12 with GCC 7.1.0

### ISSUE THREAD

**Issue by fxcoudert** [sourceryinstitute/OpenCoarrays#374] opened 2017-05-04 07:46 UTC
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

# Defect/bug report #

Tests `10 - async_comp_alloc` and `37 - convert-before-put` fail for OpenCoarrays-1.8.8 built on macOS 10.12 (but also on 10.11 and 10.10) with newly-released GCC 7.1.0. MPI is open-mpi 2.1.0. See full output below.

Homebrew issue: https://github.com/Homebrew/homebrew-core/pull/13219

```
==> ctest --output-on-failure --schedule-random
Test project /tmp/opencoarrays-20170504-32654-fl32gd/OpenCoarrays-1.8.8/build
      Start  4: register_alloc_vector
 1/43 Test  #4: register_alloc_vector ............   Passed    0.11 sec
      Start 11: get_array
 2/43 Test #11: get_array ........................   Passed    0.19 sec
      Start 20: co_min
 3/43 Test #20: co_min ...........................   Passed    0.17 sec
      Start 37: convert-before-put
 4/43 Test #37: convert-before-put ...............***Failed  Required regular expression not found.Regex=[Test passed.
]  0.14 sec
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
 Test failed on image            2 : received    0.00000000     , expected    2.00000000    
ERROR STOP 
 Test failed on image            3 : received    0.00000000     , expected    3.00000000    
ERROR STOP 
[Sierra-2.local:33900] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[Sierra-2.local:33900] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

      Start 24: syncimages2
 5/43 Test #24: syncimages2 ......................   Passed    0.18 sec
      Start  3: register_vector
 6/43 Test  #3: register_vector ..................   Passed    0.10 sec
      Start 28: syncimages_status
 7/43 Test #28: syncimages_status ................   Passed    0.22 sec
      Start  5: allocate_as_barrier
 8/43 Test  #5: allocate_as_barrier ..............   Passed    1.11 sec
      Start 39: co_reduce-factorial
 9/43 Test #39: co_reduce-factorial ..............   Passed    0.25 sec
      Start  2: register
10/43 Test  #2: register .........................   Passed    0.11 sec
      Start 41: co_reduce-factorial-int64
11/43 Test #41: co_reduce-factorial-int64 ........   Passed    0.31 sec
      Start 21: co_max
12/43 Test #21: co_max ...........................   Passed    0.23 sec
      Start  1: initialize_mpi
13/43 Test  #1: initialize_mpi ...................   Passed    0.11 sec
      Start 15: whole_get_array
14/43 Test #15: whole_get_array ..................   Passed    0.12 sec
      Start 16: strided_get
15/43 Test #16: strided_get ......................   Passed    0.10 sec
      Start  8: register_alloc_comp_2
16/43 Test  #8: register_alloc_comp_2 ............   Passed    0.11 sec
      Start 19: co_broadcast
17/43 Test #19: co_broadcast .....................   Passed    0.36 sec
      Start 33: coarray_burgers_pde
18/43 Test #33: coarray_burgers_pde ..............   Passed    0.13 sec
      Start 38: event-post
19/43 Test #38: event-post .......................   Passed    0.11 sec
      Start 34: co_heat
20/43 Test #34: co_heat ..........................   Passed    1.15 sec
      Start 31: simpleatomics
21/43 Test #31: simpleatomics ....................   Passed    0.31 sec
      Start 23: syncimages
22/43 Test #23: syncimages .......................   Passed    0.25 sec
      Start 27: co_reduce_res_im
23/43 Test #27: co_reduce_res_im .................   Passed    0.24 sec
      Start 14: get_with_offset_1d
24/43 Test #14: get_with_offset_1d ...............   Passed    0.11 sec
      Start 18: co_sum
25/43 Test #18: co_sum ...........................   Passed    0.17 sec
      Start 32: hello_multiverse
26/43 Test #32: hello_multiverse .................   Passed    0.11 sec
      Start 10: async_comp_alloc
27/43 Test #10: async_comp_alloc .................***Timeout   3.61 sec
 known failure -- ctest will timeout (see https://github.com/sourceryinstitute/opencoarrays/issues/260).
           1 /           4 : allocating_image=           1
           1 /           4 : allocating...
           3 /           4 : allocating_image=           1
           2 /           4 : allocating_image=           1
           4 /           4 : allocating_image=           1

      Start 22: syncall
28/43 Test #22: syncall ..........................   Passed    1.27 sec
      Start 12: get_self
29/43 Test #12: get_self .........................   Passed    0.11 sec
      Start 26: co_reduce
30/43 Test #26: co_reduce ........................   Passed    0.26 sec
      Start 29: sync_ring_abort_np3
31/43 Test #29: sync_ring_abort_np3 ..............   Passed    0.12 sec
      Start 13: send_array
32/43 Test #13: send_array .......................   Passed    0.20 sec
      Start 35: asynchronous_hello_world
33/43 Test #35: asynchronous_hello_world .........   Passed    0.11 sec
      Start 42: co_reduce_string
34/43 Test #42: co_reduce_string .................   Passed    0.18 sec
      Start 17: strided_sendget
35/43 Test #17: strided_sendget ..................   Passed    0.12 sec
      Start  7: register_alloc_comp_1
36/43 Test  #7: register_alloc_comp_1 ............   Passed    0.11 sec
      Start  6: allocate_as_barrier_proc
37/43 Test  #6: allocate_as_barrier_proc .........   Passed    1.26 sec
      Start 36: source-alloc-no-sync
38/43 Test #36: source-alloc-no-sync .............   Passed    0.16 sec
      Start 25: duplicate_syncimages
39/43 Test #25: duplicate_syncimages .............   Passed    0.13 sec
      Start 30: sync_ring_abort_np7
40/43 Test #30: sync_ring_abort_np7 ..............   Passed    0.24 sec
      Start 43: test-installation-scripts.sh
41/43 Test #43: test-installation-scripts.sh .....   Passed    0.88 sec
      Start 40: co_reduce-factorial-int8
42/43 Test #40: co_reduce-factorial-int8 .........   Passed    0.32 sec
      Start  9: register_alloc_comp_3
43/43 Test  #9: register_alloc_comp_3 ............   Passed    0.10 sec

95% tests passed, 2 tests failed out of 43

Total Test time (real) =  15.91 sec

The following tests FAILED:
	 10 - async_comp_alloc (Timeout)
	 37 - convert-before-put (Failed)
Errors while running CTest
```

**Comment by zbeekman** [comment] 2017-05-04 12:33
Thanks for the bug report. These are known failures with GCC 7 and we are working to resolve them. In the mean time (the next release) we will have an additional build flag that toggles tests known to fail to developers when building with GCC 7.

 - `async_comp_alloc`: Known failure because this test is for a new feature (allocatable components of coarray derived types) which is only partially implemented and experimentally supported for now
 - `convert-before-put`: Regression because the responsibility for type conversion during coarray puts was shifted from GFortran to OpenCoarrays.

See also #342 

I'm going to close this as a duplicate of #342, #292 and #260

**Closed by zbeekman** 2017-05-04 12:33 UTC
Labels: duplicate, waiting

**Comment by fxcoudert** [comment] 2017-05-04 13:27
If the opencoarrays policy is to have "known failures", Homebrew will have to build without build-time tests, I'm afraid.

**Comment by zbeekman** [comment] 2017-05-04 13:51
> If the opencoarrays policy is to have "known failures", Homebrew will have to build without build-time tests, I'm afraid.

no, we're going to add a flag to disable the tests with known failures (#342)

that way homebrew and users can still run the build-time tests.... I'm going to get a release out ASAP probably later today with this change

**Comment by zbeekman** [comment] 2017-05-04 20:57
https://github.com/sourceryinstitute/OpenCoarrays/releases/tag/1.8.10 should be GCC 7/Homebrew ready
