### ISSUE TITLE
RFE: Use mpich >= 3.2 for trunk once failed images patch is available.

### ISSUE THREAD

**Issue by vehre** [sourceryinstitute/OpenCoarrays#355] opened 2017-04-04 17:45 UTC
# RFE: #

The failed images patch needs mpich at least of version 3.2. Therefore when trunk (gcc-7) is compiled and users want failed images support (that may be configurable in OpenCoarrays) at least version 3.2 of mpich is needed. I therefore recommend using it as default, when pulling in prerequisites, given that 3.2 is the current stable of mpich.

**Comment by zbeekman** [comment] 2017-05-01 21:22
@rouson FYI, on Mac OS MPICH 3.2 built by install.sh with gcc 6.3 seems to have segfault issues.

I took a look at the home-brew formula and noticed this:

```Ruby
# Fix segfault; remove for next mpich releaase > 3.2
    if build.stable? && ENV.compiler == :clang
      inreplace "src/include/mpiimpl.h",
        "} MPID_Request ATTRIBUTE((__aligned__(32)));",
        "} ATTRIBUTE((__aligned__(32))) MPID_Request;"
    end
```

I'm wondering if we need to do similar? I'm trying an experiment right now: compiling mpich using home-brew and gcc-6 (to mimic install.sh) and it appears that the `&& ENV.compiler == :clang` clause will cause the patch to be skipped. If the patch is indeed skipped and this also causes segfaults, then that's a pretty decent indication that we need to apply the patch on Mac OS using install.sh

**Comment by zbeekman** [comment] 2017-05-01 21:23
FYI I pushed up my latest attempt at implementing this to https://github.com/sourceryinstitute/OpenCoarrays/tree/issue-355-upgrade-mpich

**Comment by zbeekman** [comment] 2017-05-01 23:18
I confirmed that the patch fixes the Mac OS segfaults... I've added it to the installer script.

@afanfa and @vehre: Do either of you anticipate the patch will interfere with failed images?

`sed s/} MPID_Request ATTRIBUTE((__aligned__(32)));/} ATTRIBUTE((__aligned__(32))) MPID_Request;/g' src/include/mpiimpl.h`

**Comment by zbeekman** [comment] 2017-05-02 02:04
@afanfa & @vehre: never mind, here is the a link to the discussion of the bug: http://lists.mpich.org/pipermail/discuss/2016-May/004764.html The bug fix appears to preserve and correct the intended semantics.

**Comment by rouson** [comment] 2017-05-02 05:26
Pull request #372 has been merged into the master branch to increase the default MPICH version number to 3.2.

**Closed by rouson** 2017-05-02 05:26 UTC
Labels: enhancement
