### ISSUE TITLE
Ensure all tests pass with gcc-7 (trunk) and gcc-7 branch of opencoarrays

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#221] opened 2016-09-27 18:00 UTC
UPDATE (2016-12-21 by @zbeekman):
All original tests are passing with the possible exception of the NS tests under OpenMPI on docker, and a new test added by @vehre but requires more work by @afanfa on the library side, #260. Since we have separate issues for all those improvements, I'm going to investigate the NS-OMPI-GCC-trunk-Docker failures some more and then, most likely, just close this issue. I suspect the NS failures may be due to the fancy assembly FFT routines.

Fix all failing tests when using GCC-7 (trunk) and the gcc-7 branch.
- [x] 1
- [x] 9
- [x] 8
- [x] 10
- [x] 22
- [x] 24

Here is some text from @vehre elaborating on some failures he was seeing:

With these changes and the update of gcc-trunk I have only three testcases
failing:

  1 - initialize_mpi (Failed)      -- I have no clue, why this fails.
The reason for failure here is not obvious to me and I don't think it is caused
by the changes to the caf-interface.

```
 10 - whole_get_array (Failed)
```

This can be fixed, when allocatable arrays on the right-hand side of a coarray
get operation are not unnecessarily declared allocatable although they get
allocated just once with a fixed size and never change.

```
24 - coarray_navier_stokes (Failed)
```

The same as with 10.

For testcase 22 - coarray_burgers_pde I had to change the number of process to
4 in the makefile to get it running reliably with the same result. With 2
processes it always asserts.

**Comment by zbeekman** [comment] 2016-11-03 18:17
The latest GCC trunk (241802  2016-11-02) and OpenCoarrays (dfe2ec0932d7bd60064922f57afdb3ca60521146) pass all tests except for test 9: get_with_offset_1d

```
test 9
      Start  9: get_with_offset_1d

9: Test command: /usr/local/bin/mpiexec "-np" "2" "/Users/ibeekman/Sandbox/opencoarrays/build/src/tests/unit/send-get/get_with_offset_1d"
9: Test timeout computed to be: 9.99988e+06
9:
9: Program aborted. Backtrace:
9: #0  0x10eb4e949
9: #1  0x10eb4f5f4
9: #2  0x10ec25118
9: #3  0x10e7b2892
9: #4  0x10e7ba65b
9:
9: ===================================================================================
9: =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
9: =   PID 87355 RUNNING AT Izaaks-MacBook-Pro.local
9: =   EXIT CODE: 6
9: =   CLEANING UP REMAINING PROCESSES
9: =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
9: ===================================================================================
9: YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
9: This typically refers to a problem with your application.
9: Please see the FAQ page for debugging suggestions
 9/24 Test  #9: get_with_offset_1d ...............***Failed  Required regular expression not found.Regex=[Test passed.
]  0.06 sec
```

**Comment by zbeekman** [comment] 2016-11-29 02:22
All:

FYI, I have created a docker project that rebuilds every night with the latest GCC trunk. I am planning to use this to add testing against GCC trunk to our CI infrastructure, however, I *may* set these tests (with GCC trunk) to be allowed failures since we can't guarantee that GCC trunk will always build and behave correctly.

Here is the github repo: [zbeekman/docker-gcc-build](https://github.com/zbeekman/docker-gcc-build) and here is the docker hub page: https://hub.docker.com/r/zbeekman/docker-gcc-build/

The nightly rebuilds are triggered via [nightli.es](https://nightli.es) and my [zbeekman/nightly-docker-rebuild](https://github.com/zbeekman/nightly-docker-rebuild) project. I'll probably create an OpenCoarrays docker image that is triggered to rebuild nightly by the GCC image, so that the latest bleeding edge OpenCoarrays and GCC can be easily tested together.

**Comment by zbeekman** [comment] 2016-12-14 04:45
This is now true, except for under some circumstances the Navier-Stokes test (pending confirmation) and the extra test that depends on #260 getting done...

**Comment by zbeekman** [comment] 2016-12-21 15:40
I believe that all the tests pass now, with the exception of those blocked by #260 which are new...

I was seeing intermittent failure of NS test with OpenMPI on Docker images, and want to investigate more before closing this issue...

**Comment by zbeekman** [comment] 2017-01-14 19:57
I can confirm that all tests pass on OS X with GCC trunk `gcc-7 (Homebrew GCC HEAD-244466_1 --without-multilib) 7.0.0 20170114 (experimental)` except for those that have their own issues and are known regressions/defects:

 - #260 (waiting for specific features to be implemented by @afanfa)
 - #292 

As such, I'm closing this issue.

Here is what I get on Sierra:
[![asciicast](https://asciinema.org/a/99298.png)](https://asciinema.org/a/99298)

**Closed by zbeekman** 2017-01-14 19:57 UTC
Labels: in progress
