### ISSUE TITLE
Consider deleting static makefiles in all source directories

### ISSUE THREAD

**Issue by jerryd** [sourceryinstitute/OpenCoarrays#361] opened 2017-04-17 03:40 UTC
(aside: Issue template is way over kill for my purposes and discourages bothering to submit issues. IMHO should be eliminated, too complex.)

As I further development of the application of the Gnu Build System aka AutoTools (which is quite capable and more advanced than people unacquainted with it think) the existing static Makefiles will be obsoleted, as they already are by cmake as well. I wanted to capture this on the to do list. So consider deleting these from master. I am working from a fork so no impact to my work at this time. Just let everyone start thinking about it and be aware.

**Comment by rouson** [comment] 2017-04-17 14:48
@jerryd, if there are  parts of the template that you think are more useful than other arts, more specific feedback would be helpful as.  Scrapping the whole template would make it more likely that issues will be submitted that place a lot of burden on OpenCoarrays contributors without requiring users to do some up-front work.

Nothing would give me greater joy than deleting the static Makefiles but it might be safer to just deprecate their use very clearly in comments at the top of each Makefile.  The problem is that we have specific users who prefer each different build method to the exclusion of all others.  I'll check with one user who exclusively uses the static Makefiles and claims to know of no one who builds OpenCoarrays any other way. I'll also check with @afanfa who authored the Makefiles.

**Comment by rouson** [comment] 2017-04-19 16:38
I've now corresponded with two people each play important roles in the Fortran community about this.  It seems clear the Makefiles should stay in place so I'm going to close this issue.  I'll share more privately.

**Closed by rouson** 2017-04-19 16:38 UTC
