### ISSUE TITLE
allocate_as_barrier_proc fails on oversubscribe

### ISSUE THREAD

**Issue by amckinstry** [sourceryinstitute/opencoarrays#266] opened 2016-12-03 20:48 UTC
Running openmpi 2.0.1+, mpiexec -np 2 --oversubscribe, test 6 fails. when 1 core available. When 2 available, it works fine.

**Comment by rouson** [comment] 2016-12-04 01:39
@amckinstry 

Because it relates to allocate imposing a synchronization and it because the failure reported happens when np < # cores, this seems to be a duplicate of #243 so I'm closing this. If you disagree, feel free to open it.

**Closed by rouson** 2016-12-04 01:39 UTC

**Comment by zbeekman** [comment] 2016-12-05 15:13
@amckinstry do you have a link to a log? I'd like to confirm that this is in fact #243...

**Comment by amckinstry** [comment] 2016-12-05 15:21
You can see general logs here: https://buildd.debian.org/status/package.php?p=open-coarrays
(click on the "Installed" column; they're links).

Its random as it depends on which build machine the build request lands on , how many cores are available. In this case, (#266) I've a VM (virtualbox) that I can just set the number of cores and reproduce the problem. Whether it is #243, do you have a test I can run?

**Comment by zbeekman** [comment] 2016-12-05 15:50
Ok, I've looked at the source code of [allocate_as_barrier_proc.f90](https://github.com/sourceryinstitute/opencoarrays/blob/41c272ddf90466d3df55910ab3ce7468f9b775df/src/tests/unit/init_register/allocate_as_barrier_proc.f90) and it does appear to be #243... sorry for the noise. A good way to confirm this would be to add a `sync all` after [line 26](https://github.com/sourceryinstitute/opencoarrays/blob/41c272ddf90466d3df55910ab3ce7468f9b775df/src/tests/unit/init_register/allocate_as_barrier_proc.f90#L26) and then the error should go away.

**Comment by amckinstry** [comment] 2016-12-09 10:45
Just a reference: the following related patch to gfortran went through yesterday:
https://gcc.gnu.org/ml/gcc-patches/2016-12/msg00649.html

**Comment by zbeekman** [comment] 2016-12-09 17:54
@amckinstry thanks for the heads up. We work with Andre (@vehre) and a number of other GCC contributors.

Regarding debian testing, which (if any) of the docker images [listed under architectures other than ad64](https://github.com/docker-library/official-images#architectures-other-than-amd64) do you think would make a decent surrogate testing environment for me? (This might be easier/faster than getting the debian visitor paper work finished etc.)

**Comment by rouson** [comment] 2016-12-09 23:20
@amckinstry Sorry if I'm telling you something you already know: the patch was submitted for review. From looking at the mailing list, I don't see evidence that it was approved and applied to the trunk so it presumably lives on a branch that @vehre is using for development.

**Comment by vehre** [comment] 2016-12-10 11:14
> @amckinstry Sorry if I'm telling you something you already know: the patch was submitted for review. From looking at the mailing list, I don't see evidence that it was approved and applied to the trunk so it presumably lives on a branch that @vehre is using for development.

The patch for pr78505 hit trunk with r243482 as reported in https://gcc.gnu.org/ml/fortran/2016-12/msg00096.html 
I will now comment in #243, because opencoarrays needs to reflect this change.
