### ISSUE TITLE
Tests failing after Build

### ISSUE THREAD

**Issue by WilliamJamieson** [sourceryinstitute/opencoarrays#211] opened 2016-08-09 17:17 UTC
Hello, 

I am new to opencoarrays. Currently I am having issues with opencoarrays passing some of the tests (provided by ctests). Namely the tests: 
           6 - allocate_as_barrier_proc (Failed)
         16 - syncall (Failed)
         17 - syncimages (Failed)
         20 - syncimages_status (Failed)

The way I obtained/built opencoarrays was to clone the git repository (as it was this morning at 9:30am EST) and then followed the standard Cmake install instructions provided in INSTALL.md. I am using the gcc 6.1.0 compiler along with openmpi 1.10.2 (built with gcc 6.1.0), and Cmake 3.5.1.

The build was done on the NCCS discover computer (at NASA GSFC), as a local account install. Commands used where (note this was done on an interactive session starting in my home directory):

    $ salloc --ntasks-per-node=10 --nodes=2 --constraint=hasw -c 1 -t 1:00:00
    $ git clone https://github.com/sourceryinstitute/opencoarrays.git
    $ cd opencoarrays
    $ module load other/comp/gcc-6.1-sp3 other/mpi/openmpi/1.10.2-gcc-6.1-sp3 other/cmake-3.5.1
    $ mkdir opencoarrays-build
    $ cd opencoarrays-build
    $ CC=mpicc FC=mpif90 cmake .. -DCMAKE_INSTALL_PREFIX=${PWD}
    $ make
    $ ctest

Note that it gave the failures at this point and I stopped.

How do I solve these issues? Moreover, are theses failures critical, or may I use opencoarrays without issue?

**Comment by zbeekman** [comment] 2016-08-10 15:43
Hi William,

Can you please include additional details about the machine and environment you are using? Please include the following:

 1. The output of `uname -a`
 1. Any additional details about the OS (name and version)
 1. The compiler name and version
 1. The MPI implementation name and version
 1. Any peculiarities of your particular computing environment
 1. The machine name, and links to any public documentation, if using a computer at a national lab or other computing center.

Additionally, can you please include the messages output when you first invoke CMake? (I have included an example from my system at the end...)

Finally, please include the output of:

```
export CTEST_OUTPUT_ON_FAILURE=1 #assumes sh/bash, adjust for csh, etc.
ctest --verbose --extra-verbose
```

My suspicion is that--due to hyper threading or some other reason--CMake/OpenMPI thinks that there are more cores available to run the tests than there actually are. OpenMPI does __*not*__ like to be oversubscribed, and this will cause tests to fail intermittently. On my laptop, with 4 physical cores and 8 virtual cores, CMake/OMPI detect 8 available cores. Typically this doesn't cause any problems but rarely test 6 `allocate_as_barrier_proc` will still fail for me. If this is the case, then you shouldn't encounter any runtime problems, so long as you ensure that your runtime environment is __*not*__ oversubscribed. (i.e., ensure that each MPI rank gets mapped to 1 physical core.) If you were to switch MPI implementations to MPICH or mvapich the tests should still run correctly even when oversubscribed. Alternatively, look at the "Test command" for all the failed tests, and re-run each of them manually, specifying the correct number of cores.

(Tests are intentionally oversubscribed because we have found that this helps to catch some runtime errors associated with parallel programing communication and synchronization logic errors.)

Example output from initial invocation of `cmake`:

```
$ cmake ..
-- The C compiler identification is GNU 6.1.0
-- The Fortran compiler identification is GNU 6.1.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/mpicc
-- Check for working C compiler: /usr/local/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/mpif90
-- Check for working Fortran compiler: /usr/local/bin/mpif90  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/mpif90 supports Fortran 90
-- Checking whether /usr/local/bin/mpif90 supports Fortran 90 -- yes
-- Performing Test Check_Simple_Coarray_Fortran_Source_Compiles
-- Performing Test Check_Simple_Coarray_Fortran_Source_Compiles - Success
-- Found MPI_C: /usr/local/homebrew/Cellar/open-mpi/1.10.2_1/lib/libmpi.dylib
-- Found MPI_Fortran: /usr/local/homebrew/Cellar/open-mpi/1.10.2_1/lib/libmpi_usempif08.dylib;/usr/local/homebrew/Cellar/open-mpi/1.10.2_1/lib/libmpi_usempi_ignore_tkr.dylib;/usr/local/homebrew/Cellar/open-mpi/1.10.2_1/lib/libmpi_mpifh.dylib;/usr/local/homebrew/Cellar/open-mpi/1.10.2_1/lib/libmpi.dylib
-- OpenMPI detected
-- Test allocate_as_barrier_proc is oversubscribed: 32 ranks requested with 8 system processor available.
-- Open-MPI detected, over-riding oversubscribed test, allocate_as_barrier_proc, with 8 ranks.
-- Test syncall is oversubscribed: 32 ranks requested with 8 system processor available.
-- Open-MPI detected, over-riding oversubscribed test, syncall, with 8 ranks.
-- Test syncimages is oversubscribed: 32 ranks requested with 8 system processor available.
-- Open-MPI detected, over-riding oversubscribed test, syncimages, with 8 ranks.
-- Test syncimages_status is oversubscribed: 32 ranks requested with 8 system processor available.
-- Open-MPI detected, over-riding oversubscribed test, syncimages_status, with 8 ranks.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ibeekman/Sandbox/opencoarrays/build
```

**Comment by afanfa** [comment] 2016-08-11 02:40
Dear William,
I'm not able to reproduce the problem using gcc-6.1.0, openmpi-1.10.2 and cmake 3.5.2 on my linux-x86_64.
As suggested by @zbeekman , please use (if possible) mpich or mvapich and let us know how it goes.  
I don't it is important for solving this problem, anyway you should also type "make install" after the make and before ctest.

Cheers,
Alessandro

**Comment by rouson** [comment] 2016-09-05 07:16
Given that we can't reproduce this problem, the report is 27 days old, and the responses to the report are 25-26 days old, I'm closing it.  @WilliamJamieson, feel free to reopen it if you're still having a problem.

**Closed by rouson** 2016-09-05 07:16 UTC
