### ISSUE TITLE
Defect: internal error when accessing array-coarray of derived type with allocatable component

### ISSUE THREAD

**Issue by hsnyder** [sourceryinstitute/OpenCoarrays#739] opened 2021-10-05 16:17 UTC
The following program produces incorrect results. The line marked `! NOTE` should print 1, 2, 3, 4, but instead I get "OpenCoarrays internal error on image 2: libcaf_mpi::caf_sendget_by_ref(): can not allocate 0 bytes of memory."

Versions:
```
GCC 11.2.0
OpenCoarrays 2.9.2
MPICH 3.2
```
```
program bug
    type :: container
        integer, allocatable :: stuff(:)
    end type

    type(container) :: co_containers(10)[*]

    if (this_image() == 1) then
        allocate(co_containers(2)%stuff(4))
        co_containers(2)%stuff = [1,2,3,4]
    end if

    sync all

    if (this_image() == 2) then
        print *, co_containers(2)[1]%stuff  ! NOTE
    end if
end program
```

**Comment by rouson** [comment] 2022-11-08 21:19
@vehre this has entered our critical path for a paper draft due in December.  Any chance you can work on a fix soon?

**Comment by vehre** [comment] 2022-11-09 08:07
@rouson I can find some time to work on this, but I have to report: The example in the description works for me on:

- gfortran 11.3.1, fedora 35 system supplied
- mpich 3.4.1, fedora 35 system supplied
- opencoarrays 2.10.1, self-compiled

Only the one in the link in [Link to the somewhat larger demonstrator](https://github.com/rouson/bug-reports/blob/a212a1c06b6ba2862d13d724454b466f9c975563/src/gnu/nrc/coarray-with-nested-allocatable-components/intel-18-works.f90) crashes on init, with an `PMPI_Win_allocate: Invalid topology,...` error. If you want me to investigate further, just let me know.

**Comment by rouson** [comment] 2022-11-09 12:29
@vehre Yes, please investigate further.  @everythingfunctional encountered this same issue yesterday.  I'll let him confirm his setup.  I have a broken installation at the moment after problems with a macOS upgrade so I'm not able to confirm this immediately.

**Comment by vehre** [comment] 2022-11-10 14:16
@rouson I have analysed the issue further: The code generated for managing the allocatable component of the type in the module does not take into account that the type could be used in a coarray. I.e. there is no space assigned (at compile time) to keep track of the allocation status and the coarray (slave) token. Furthermore is because of this no code generated to define "a mpi window" for the allocated memory, which prevents the one image from the accessing this memory on the other image.

Or with other words: Solving this issue is nothing quick to be done, but some bigger effort. One needs to find a way to portably generate the code of the module to either always call coarray-registration routines for every memory allocated in a module when the compile flag -fcoarray=lib is given or to create two instances of the code to execute for each module, one with coarray support and one without. 

How to proceed?

**Comment by rouson** [comment] 2022-11-10 15:31
@vehre thanks for the quick reply.  If this had been a quick fix, Sourcery Institute could have funded it.  Because its a larger effort, I'll need to seek alternative funding. Please email me a rough estimate at your earliest convenience.

**Comment by rouson** [comment] 2022-12-06 21:31
The reproducer submitted in the original comment for this issue has been fixed on the main branch and will appear in the 2.10.1 release, which currently has draft release notes. @everythingfunctional please create a new issue with the from comment your issue comment [above](https://github.com/sourceryinstitute/OpenCoarrays/issues/739#issuecomment-1308873497) and link to @vehre's [comment](https://github.com/sourceryinstitute/OpenCoarrays/issues/739#issuecomment-1310344329).

**Closed** 2022-12-06 21:31 UTC
